### ISSUE TITLE
Logging large objects messes up AWS CloudWatch console

### ISSUE THREAD

**Issue by tobiiasl** [tobiipro/minlog#25]
Logging a return value from a call to `axios` in an AWS lambda function using minlog messed up the CloudWatch console so that log entries was not shown and the ones that were shown were incomplete and difficult to read. Probably because the stringified version of the object got very long.

   Logging it with `console.log` worked fine and did not have that effect.

**Comment by andreineculau** [comment]
notes2self:

* we could limit the JSON depth, but that wouldn't fix e.g. a top-level Buffer from being stringified to potentially a really long output
* could limit the size of strings, array, objects values
* could limit (truncate) the size of of the entire output - means truncated invalid JSON, but maybe it's still better than today's scenario
* could limit the size of the entire output, and if bigger than a threshold, stick to using util.inspect (console.log behavior) rather than JSON.stringify values

the last alternative seems to be the cleanest

**Comment by andreineculau** [comment]
i believe this has been addressed by implementing the jsonStringifyReplacer in https://github.com/tobiipro/minlog/commit/b8283e58d681d219b48831de1fafed2814731dc0#diff-8cd4968b81985f0efc2053eabc37db6d
